name: Actualizar Agenda

on:
  schedule:
    - cron: '*/30 * * * *' # Cada 30 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install puppeteer

      - name: Ejecutar scraping
        run: node scrape.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Confirmar y subir cambios
        run: |
          git add agenda.json
          git commit -m "Actualizar agenda deportiva" || echo "No hay cambios"
          git push
