name: Scrape Agenda

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scrape.js

      - name: Commit y push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add agenda.json
          git commit -m "Update agenda" || echo "No changes"
          git push
